spring:
  h2:
    console:
      enabled: true
      settings:
        trace: false
  flyway:
    enabled: true
    user: sa
    password: pass

datasource:
  db:
    url: jdbc:h2:./test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: pass

financing:
  processing:
    batchSize: 1000
    threads: 10