spring:
  jpa:
    generate-ddl: false
  datasource:
    url: jdbc:h2:./test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        trace: false
  flyway:
    enabled: true
    user: sa
    password:

#logging:
#  level:
#    root: debug